const DEG = 0.0174533

const DEG_TO_RAD = DEG

const DASH_OFFSET_DELTA = 0.0005

const TAU = Math.PI * 2.0

const SQRT3 = Math.sqrt(3.0)

const NUM_ABLETON_MIDI_CHANNELS = 16

export { DEG, DEG_TO_RAD, DASH_OFFSET_DELTA, TAU, SQRT3, NUM_ABLETON_MIDI_CHANNELS }
